### ISSUE TITLE
At times generates 1 digit OTP

### ISSUE THREAD

**Issue by vibindhas** [AqibMukhtar/in-memory-otp#2]
I think we can have a configuration to set the number of digits needed in OTP and generate based on that.

have a function like below

let OTPDigits = 4;
```
function getOTP() {
    let otp = '';
    for (let i = 0; i < OTPDigits; i++ ) {
        otp += Math.floor(Math.random() * 10);
    }
    return Number(otp);
}
```
Call this method from generateOTP

**Comment by AqibMukhtar** [comment]
@vibindhas thank you so much for the fix. 😍

**Comment by AqibMukhtar** [comment]
The pull request has been approved and successfully merged. Thanks again
